config/routes.rb
Gtf::Application.routes.draw do

  root :to     => "pages#home"
  get "/about" => "pages#about"

  resources :keywords
  resource :feedback
end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  has_many :keyword_data

  def to_param
    CGI.escape(name)
  end
end

app/models/keyword_data.rb
class KeywordData < ActiveRecord::Base
  belongs_to :keyword
  after_create :update_keyword_searches

  private

    def update_keyword_searches
      keyword.update_attributes(:searches => keyword.searches ? keyword.searches + data : data)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/feedback_controller.rb
class FeedbackController < ApplicationController
  def show
  end

  def create
  end
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  def index
    @search = Keyword.search(params[:q])
    @search.sorts = 'searches DESC' if @search.sorts.empty?
    @keywords = @search.result.paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @keyword = Keyword.find_by_name(CGI.unescape(params[:id]))
    if @keyword.nil?
      flash[:error] = 'Keyword is not found'
      redirect_to root_path
    else
      @chart_data =
        (1.month.ago.to_date..Date.today).map { |date|
          point = @keyword.keyword_data.find_by_collected_at(date.at_midnight)
          point.nil? ? nil : point.data
        }
      render 'show'
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @keywords = Keyword.limit(10).order(searches: :desc)
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/feedback/create.html.haml
%h1 Feedback#create
%p Find me in app/views/feedback/create.html.haml

app/views/feedback/show.html.haml
- provide(:title, 'Feedback')
.page-header
  %h1
    Feedback

app/views/keywords/_keyword.html.haml
.row
  .col-md-8
    = link_to keyword.name, keyword
  .col-md-4
    = keyword.searches

app/views/keywords/index.html.haml
- provide(:title, 'Keywords')
.page-header
  %h1
    Keywords
= search_form_for @search do |f|
  = f.label :name_cont, "Keyword contains"
  = f.text_field :name_cont
  = f.submit "Search"
= will_paginate @keywords, renderer: BootstrapPagination::Rails
.row
  .col-md-8.well
    .row
      .col-md-8
        %h4
          = sort_link @search, :name, 'Keyword'
      .col-md-4
        %h4
          = sort_link @search, :searches, 'No. of Searches'
    = render @keywords

app/views/keywords/show.html.haml
- provide(:title, @keyword.name)
= javascript_include_tag 'application', 'highcharts/highcharts.js'
:coffeescript
  ready = ->
    $.fn.showChart(#{@chart_data.to_json})
  $(document).ready(ready)
  $(document).on('page:load', ready)
.page-header
  %h1
    = @keyword.name
.row
  #chart.col-md-8.well
%h3
  = link_to '< Back to Keywords', keywords_path

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Twitter Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Twitter Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Global Trend Finder', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
%li{class: current_page?(root_path) ? 'active' : nil}
  = link_to 'Home', root_path
%li{class: current_page?(keywords_path) ? 'active' : nil}
  = link_to 'Keywords', keywords_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? ENV['TITLE'] + ' - ' + yield(:title) : ENV['TITLE']
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : ENV['TITLE']}"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = javascript_include_tag 'application', 'fb-sdk'
    = javascript_include_tag 'application', 'twitter'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      .container
        = yield
    %footer
      .container
        %ul.nav.nav-pills.pull-left
          %li{class: current_page?(about_path) ? 'active' : nil}= link_to 'About', about_path
          %li{class: current_page?(feedback_path) ? 'active' : nil}= link_to 'Feedback', feedback_path
        %ul.nav.nav-pills.pull-right
          %li.social-icons
            .fb-like{'data-font' => 'arial',
                     'data-href' => 'http://global-trend-finder.com',
                     'data-layout' => 'button_count',
                     'data-send' => 'false',
                     'data-show-faces' => 'true',
                     'data-width' => '150'}
          %li.social-icons
            %a.twitter-share-button{'data-hashtags' => 'globaltf,google',
                                    'data-lang' => 'en',
                                    'data-text' => 'Fun Google Autocomplete Queries',
                                    'data-url' => 'http://global-trend-finder.com',
                                    href: 'https://twitter.com/share'} Tweet

app/views/pages/about.html.haml
- provide(:title, 'About')
.page-header
  %h1
    About
.row
  .col-md-8.well
    %h2 Why is this all?
    %p
      Ever wondered, how
      = link_to 'Google Autocomplete', 'http://support.google.com/websearch/bin/answer.py?hl=en&answer=106230', target: '_blank'
      works? How it decides which phrases to offer?
    %p
      Maybe you were just curious how many gems
      = link_to 'like', 'http://failblog.org/tag/autocomplete-me', target: '_blank'
      = link_to 'these', 'http://www.searchenginepeople.com/blog/google-autocomplete-fails.html', target: '_blank'
      are remain to be found?
    %p
      This tool goes through the list of the most popular English words and feeds them to
      Google Autocomplete API. Results are updated daily, and if we're finding something
      that looks like a website, we put it in a separate table.

app/views/pages/home.html.haml
.page-header
  %h1
    Top 10 Keywords
.row
  .col-md-8.well
    .row
      .col-md-8
        %h4
          Keyword
      .col-md-4
        %h4
          No. of Searches
    = render @keywords
%h3
  = link_to 'Show More >', keywords_path